"""add invite table

Revision ID: 157ba31a6e78
Revises: 8874c8aa1190
Create Date: 2023-12-02 18:31:14.175441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157ba31a6e78'
down_revision: Union[str, None] = '8874c8aa1190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invites', sa.Column('user_sender_id', sa.Integer(), nullable=False))
    op.add_column('user_invites', sa.Column('user_inviter_id', sa.Integer(), nullable=False))
    op.add_column('user_invites', sa.Column('target_workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_invites_workspace_id_fkey', 'user_invites', type_='foreignkey')
    op.drop_constraint('user_invites_user_id_fkey', 'user_invites', type_='foreignkey')
    op.create_foreign_key(None, 'user_invites', 'workspace', ['target_workspace_id'], ['id'])
    op.create_foreign_key(None, 'user_invites', 'user', ['user_sender_id'], ['id'])
    op.create_foreign_key(None, 'user_invites', 'user', ['user_inviter_id'], ['id'])
    op.drop_column('user_invites', 'user_id')
    op.drop_column('user_invites', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invites', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_invites', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_invites', type_='foreignkey')
    op.drop_constraint(None, 'user_invites', type_='foreignkey')
    op.drop_constraint(None, 'user_invites', type_='foreignkey')
    op.create_foreign_key('user_invites_user_id_fkey', 'user_invites', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_invites_workspace_id_fkey', 'user_invites', 'workspace', ['workspace_id'], ['id'])
    op.drop_column('user_invites', 'target_workspace_id')
    op.drop_column('user_invites', 'user_inviter_id')
    op.drop_column('user_invites', 'user_sender_id')
    # ### end Alembic commands ###
