"""change admin field into Workspace by ForeignKey

Revision ID: 1f8a3dadd080
Revises: 4053c3a9c8cc
Create Date: 2023-12-02 20:09:28.555502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8a3dadd080'
down_revision: Union[str, None] = '4053c3a9c8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace', 'admin',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'workspace', 'user', ['admin'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.alter_column('workspace', 'admin',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
