"""Add Status in Task

Revision ID: 3ff6bd07779f
Revises: 7927152a8f31
Create Date: 2024-01-07 14:58:15.490166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff6bd07779f'
down_revision: Union[str, None] = '7927152a8f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('task', 'executor',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'executor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
