"""add admin field into Workspace

Revision ID: 4053c3a9c8cc
Revises: c690290895d8
Create Date: 2023-12-02 20:07:39.452973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4053c3a9c8cc'
down_revision: Union[str, None] = 'c690290895d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('admin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'admin')
    # ### end Alembic commands ###
